name: Trigger auto deployment for waan-album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/waan-album-api-AutoDeployTrigger-17a14808-1802-47c7-9936-024868a4e604.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca74966f9248acr.azurecr.io
          username: ${{ secrets.WAANALBUMAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.WAANALBUMAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca74966f9248acr.azurecr.io/waan-album-api:${{ github.sha }}
          file: ./src/Dockerfile
          context: ./src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WAANALBUMAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n waan-album-api -g waan-album-containerapps --server ca74966f9248acr.azurecr.io --username  ${{ secrets.WAANALBUMAPI_REGISTRY_USERNAME }} --password ${{ secrets.WAANALBUMAPI_REGISTRY_PASSWORD }}
            az containerapp update -n waan-album-api -g waan-album-containerapps --image ca74966f9248acr.azurecr.io/waan-album-api:${{ github.sha }}
